import Head from 'next/head'
import { ReactNode } from 'react'

export const RootLayout = ({children}: {
	children: ReactNode
}) => {
	return (
		<>
			<Head>
				<title>Your ChatGPT</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			
			<main className={'w-screen h-screen'}>
				{children}
			</main>
		</>
	)
}
