import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Your ChatGPT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={'w-screen h-screen'}>
        <div className={'flex w-full h-full'}>
          <div className={'hidden md:block w-[240px] bg-bg-shade'}>
            sidebar
          </div>
          
          <div className={'flex-1'}>
            content
          </div>
          
        </div>
      </main>
    </>
  )
}
