import Head from 'next/head'
import { ReactNode, useEffect } from 'react'
import { useVisitorData } from '@fingerprintjs/fingerprintjs-pro-react'
import { NavBarComp } from '@/components/shared/NavBarComp'
import { useAppDispatch, useAppSelector } from '@/states/hooks'
import { initUser } from '@/states/thunks/user'
import { selectNotifications, setTopNotification } from '@/states/features/notificationSlice'
import { useSession } from 'next-auth/react'

export const RootLayout = ({ children, title = '玩转无限可能' }: {
	children: ReactNode
	title?: string
}) => {
	const dispatch = useAppDispatch()
	const { data: session } = useSession()
	const { data: visitorData, error } = useVisitorData()
	const notifications = useAppSelector(selectNotifications)
	
	const sessionUserId = session?.user.id
	const visitorUserId = visitorData?.visitorId
	const user_id = sessionUserId || visitorUserId
	
	useEffect(() => {
		console.log(JSON.stringify({sessionUserId, visitorUserId, user_id}))
		if (user_id) {
			dispatch(initUser(user_id))
		} else if (error) {
			if (error.name === 'FPJSAgentError') {
				dispatch(setTopNotification('网络连接失败，或更换使用Google、Firefox浏览器！'))
			}
		}
	}, [user_id, error])
	
	return (
		<>
			<Head>
				<title>Your ChatGPT</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name={'viewport'} content={'width=device-width, user-scalable=no'}/>
				<link rel="icon" href="/public/favicon.ico"/>
			</Head>
			
			<main className={'w-screen h-screen flex flex-col'}>
				
				{notifications.top && (
					<div className={'bg-red-800 text-white p-4 flex justify-center items-center'}>
						{notifications.top}
					</div>
				)}
				
				<NavBarComp title={title}/>
				
				{children}
			</main>
		</>
	)
}
